db:
  image: kamui/postgresql
  environment:
  - POSTGRESQL_DB=soroban_dev
  - POSTGRESQL_USER=postgress
  - POSTGRESQL_PASS=postgress

web:
  build: .
  ports:
    - "49235:4000"
  links:
    - db:dockerdb
  volumes:
  - .:/app
  - /app/node_modules
  environment:
    - MIX_ENV=dev
#  command: elixir --erl "-smp disable" -S mix do ecto.migrate, phoenix.server
